src/components/header.component.js
src/components/loginform.component.js
src/components/sidebar.component.js

You can no longer log in when you are already logged in. If you are not logged in and you try to access another page than the log in page you will be sent to log in. Also added a log out button that deletes cookies.

Fixed some log in things and added log out

---

src/App.js
src/css/body.css
src/css/header.css
src/css/loginform.css

Removed header from login + some CSS :)

---

src/components/header.component.js
src/css/header.css

Dropdown menu works properly

---

src/App.js

Added the sidebar to the NoMatch page so the user can use it to find the right page.

NoMatch page now loads sidebar

---

src/App.js
src/components/afleveringer.component.js
src/css/afleveringer.css

Du skal lave din dansk aflevering Rasmus :)

Aflvering component

---

src/components/loginform.component.js
src/css/loginform.css

Loginform css and logo added

---

server/server.js
src/components/skema.component.js
src/components/skemabrik.component.js
src/css/sidebar.css
src/css/skema.css
src/css/skemabrik.css

UwU Peer programmed with Sigurd

Five day schedule view works kinda

---

src/components/skema.component.js
src/components/timeIndicator.component.js
src/css/skema.css
src/css/timeIndicator.css

#139 Indicator is working for only 5-day view.

Time Indicator is working

---

src/components/skema.component.js
src/components/skemabrik.component.js
src/css/skema.css
src/css/skemabrik.css
src/css/timeIndicator.css

one day view almost completely fixed

---

src/components/skema.component.js
src/components/skemabrik.component.js
src/css/skema.css

Fixed one day view

---

src/components/skema.component.js
src/components/skemabrik.component.js
src/css/skema.css

FiveDaySchedule looks pretty nice

FiveDayView shows all 5 days also added colour to the scheduleContainerHeader

---

src/components/skema.component.js

Fixed timeindicator

---

src/components/header.component.js
src/components/skemabrik.component.js
src/css/sidebar.css
src/css/skema.css

Also made a few css components scalable.

Adjusted height of schedule

---

src/components/skema.component.js
src/css/skema.css

Removed border around the entire schedule and added a slight drop shadow.

Schedule css update + CSS tidy

---

src/components/assignments.component.js
src/css/afleveringer.css
src/css/skemabrik.css

Fixed assignments by giving it the right class and removed unnecessary position: relative from css.

Fixed assignments + removing some unnecessary styling

---

src/components/assignments.component.js
src/components/skema.component.js

Schedule and assignments now only highligths the current day and not just current day of the week

---

src/components/skema.component.js
src/utils/addDays.js

Just adding some crust

---

src/components/skema.component.js

minor crust fix

---

src/App.js

redigerSkema Route only available for teachers

---

src/utils/getWeek.js

Fixed date fuckery with getWeek

---

src/components/skema.component.js
src/components/skemabrik.component.js
src/css/afleveringer.css
src/utils/getWeek.js

getWeek was still messing with the date but that is fixed now

Fixed assignments related stuff and getWeek

---

src/components/timeIndicator.component.js

"position: absolute;" was set in the render and in the CSS. It is now only in the CSS.

Indicator now updates every minute, removed repeated code, & timeIndicator.component code is commented.

---

src/components/skemabrik.component.js

The position is now offset by an hour if it is an assignment card

---

src/components/editLesson.component.js
src/components/skemabrik.component.js
src/components/skemabrikModal.component.js
src/css/modals.css

Added a new crusty component for edit lesson

---

src/components/skemabrikForm.component.js

Added default value to create lesson

---

src/components/skema.component.js

Removing some crust

---

src/components/skema.component.js

fixed position of a comment

---

src/components/skema.component.js

removed unnecessary values at function call

crust fixing

---

src/components/skema.component.js

Removing unnecessary conditional statement

---

src/components/skema.component.js
src/components/timeIndicator.component.js

cleaner code and no more scroll

Uncrusted skema.component and timeindicator only renders from 8 till 16

---

server/routes/assignments.js
server/server.js
src/components/editLessonModal.component.js
src/components/skemabrikModal.component.js
src/css/skemabrikForm.css

Edit assignment works (guaranteed crust-free)

---

src/css/modals.css

Fixed blur on assignment modal

---

server/server.js
src/components/editLessonModal.component.js

error is received now and keys have been added to editLessonModal

---

src/components/editLessonModal.component.js

removed unnecessary code from editlessonmodal

---

src/components/editLessonModal.component.js
src/components/skema.component.js

Assignments page now says it failed loading assignments

---

src/components/skemabrik.component.js
src/components/skemabrikModal.component.js

cleaning the code a bit
